run:
  concurrency: 12
  deadline: 120s
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
      - opinionated
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
#    - lll
  fast: false
