sudo: false
language: go
go_import_path: github.com/ccamel/kynaptik
go:
  - 1.12.4

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - go get github.com/mattn/goveralls
  - make install-tools
  - travis_retry make install-deps

jobs:
  include:
    - stage: build
      script:
        - make lint
        - make build
        - env GO111MODULE=on goveralls -service=travis-ci
