sudo: false
language: go
go_import_path: github.com/ccamel/kynaptik
go:
  - 1.12.4

before_install:
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: build
      script:
        - make lint
        - make build
        - env GO111MODULE=on goveralls -service=travis-ci
