apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: webhook
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps:
  - name: webhook
    namespace: default
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: EntryPoint
    packageref:
      name: kynaptik-http-dev
      namespace: default
  resources: {}
  secrets: null
