apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: webhook
  namespace: default
spec:
  contentType: application/json
  errorTopic: ""
  functionref:
    functionweights: null
    name: webhook
    type: name
  maxRetries: 0
  messageQueueType: kafka
  respTopic: output
  topic: input
